package com.foo.test_record_vector;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class bus_dim implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public bus_dim() {
    }




}