package com.foo.test_record_vector;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class data_bus_dim_test implements java.io.Serializable {

  
  
	static final long serialVersionUID = 1L;

    private java.lang.String dim_name;
	private java.lang.Long dim_levels__level_0;
	private java.lang.Long dim_levels__level_1;
	private java.lang.Long dim_levels__level_2;
	
	public java.lang.Long give_level(java.lang.Long ind) {
      if (ind == 1) return dim_levels__level_0;
      else return dim_levels__level_0;
      
	}

	public data_bus_dim_test() {
	}

	public java.lang.String getDim_name() {
		return this.dim_name;
	}

	public void setDim_name(java.lang.String dim_name) {
		this.dim_name = dim_name;
	}
	
	public java.lang.Long getDim_levels__level_0() {
		return this.dim_levels__level_0;
	}

	public void setDim_levels__level_0(java.lang.Long dim_levels__level_0) {
		this.dim_levels__level_0 = dim_levels__level_0;
	}

	public java.lang.Long getDim_levels__level_1() {
		return this.dim_levels__level_1;
	}

	public void setDim_levels__level_1(java.lang.Long dim_levels__level_1) {
		this.dim_levels__level_1 = dim_levels__level_1;
	}

	public java.lang.Long getDim_levels__level_2() {
		return this.dim_levels__level_2;
	}

	public void setDim_levels__level_2(java.lang.Long dim_levels__level_2) {
		this.dim_levels__level_2 = dim_levels__level_2;
	}

}